import { ExaminationBlueprint } from '../../types';
import { AgentResponse, PlannerAgentInput } from './types';
import { GoogleGenAI } from '@google/genai';

export class PlannerAgent {
  static async createBlueprint(input: PlannerAgentInput): Promise<AgentResponse<ExaminationBlueprint>> {
    const timestamp = new Date().toISOString();
    const headings = Array.from(new Set(input.chunks.map((c) => c.heading))).filter(Boolean);
    const chunkSample = input.chunks.slice(0, 10).map(c => `[Heading: ${c.heading}] ${c.chunkContent.substring(0, 200)}`).join('\n');

    let overview = `Autonomous oral examination strategy generated by Gemma PlannerAgent for ${input.subjectTitle}. Covers theoretical mechanics, practical application, and edge-case reasoning based on uploaded study materials.`;
    let topics = headings.length > 0 ? headings : [
      'Foundational Conceptual Mechanics',
      'Theoretical Principles & Invariants',
      'Practical Implementation & System Design',
      'Architectural Trade-offs & Failure Modes',
    ];
    let topicWeightages: Record<string, number> = {};
    topics.forEach((t, i) => {
      topicWeightages[t] = Math.round(100 / topics.length);
    });

    let difficultyProgression = [
      '1. Foundational Recall & Core Definitions',
      '2. Intermediate Conceptual Mechanism & Workflow',
      '3. Advanced Application & Failure Scenarios',
      '4. Critical Synthesis & System Trade-offs',
    ];

    let bloomTaxonomyDistribution = {
      Remembering: 15,
      Understanding: 25,
      Applying: 30,
      Analyzing: 20,
      Evaluating: 10,
    };

    let estimatedDuration = '15 - 20 Minutes';
    let questionStrategy = 'Adaptive Socratic Probing: Begins with foundational concepts, dynamically increases rigor upon correct answers, and pivots to misconception testing when superficial answers are detected.';
    let sampleProbingAngles = [
      'Deconstruct the failure modes when edge constraints or invalid inputs occur.',
      'Differentiate between theoretical assumption vs practical engineering trade-offs.',
      'Explain the mathematical or logical intuition behind the primary algorithm.',
    ];

    // Try Gemini / Gemma API if key available
    if (process.env.GEMINI_API_KEY) {
      try {
        const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
        const prompt = `You are Gemma PlannerAgent, an autonomous academic examination planner.
Analyze the following course study material chunks and generate a structured Examination Blueprint for a 15-minute oral viva examination.

Subject Title: ${input.subjectTitle}
Sample Material Chunks:
${chunkSample || 'Standard curriculum material.'}

Return JSON strictly in this format:
{
  "overview": "2-3 sentence overview of the examination strategy",
  "topics": ["Topic 1", "Topic 2", "Topic 3", "Topic 4"],
  "topicWeightages": { "Topic 1": 30, "Topic 2": 25, "Topic 3": 25, "Topic 4": 20 },
  "difficultyProgression": [
    "Phase 1: Foundational Recall & Core Definitions",
    "Phase 2: Intermediate Mechanism & Workflow",
    "Phase 3: Applied Scenario & Edge Cases",
    "Phase 4: Synthesis & Architectural Evaluation"
  ],
  "bloomTaxonomyDistribution": {
    "Remembering": 15,
    "Understanding": 25,
    "Applying": 30,
    "Analyzing": 20,
    "Evaluating": 10
  },
  "estimatedDuration": "15 - 20 Minutes",
  "questionStrategy": "Dynamic adaptive questioning style and pivot triggers",
  "sampleProbingAngles": [
    "Specific challenging probing question 1",
    "Specific challenging probing question 2",
    "Specific challenging probing question 3"
  ]
}`;

        const res = await ai.models.generateContent({
          model: 'gemini-2.0-flash',
          contents: prompt,
          config: { responseMimeType: 'application/json' },
        });

        if (res.text) {
          const parsed = JSON.parse(res.text);
          if (parsed.overview) overview = parsed.overview;
          if (parsed.topics?.length) topics = parsed.topics;
          if (parsed.topicWeightages) topicWeightages = parsed.topicWeightages;
          if (parsed.difficultyProgression) difficultyProgression = parsed.difficultyProgression;
          if (parsed.bloomTaxonomyDistribution) bloomTaxonomyDistribution = parsed.bloomTaxonomyDistribution;
          if (parsed.estimatedDuration) estimatedDuration = parsed.estimatedDuration;
          if (parsed.questionStrategy) questionStrategy = parsed.questionStrategy;
          if (parsed.sampleProbingAngles?.length) sampleProbingAngles = parsed.sampleProbingAngles;
        }
      } catch (err) {
        console.warn('Gemma PlannerAgent API fallback:', err);
      }
    }

    const blueprint: ExaminationBlueprint = {
      id: `bp-${Date.now()}`,
      subjectId: input.subjectId,
      title: `${input.subjectTitle} Examination Strategy Blueprint`,
      generatedAt: timestamp,
      status: 'draft',
      strategyData: {
        overview,
        topics,
        topicWeightages,
        difficultyProgression,
        bloomTaxonomyDistribution,
        estimatedDuration,
        questionStrategy,
        recommendedPersonas: ['socratic', 'rigorous', 'industry'],
        sampleProbingAngles,
      },
    };

    return {
      agentName: 'PlannerAgent',
      timestamp,
      success: true,
      data: blueprint,
      reasoningTrace: `Gemma PlannerAgent analyzed ${input.chunks.length} syllabus chunks across ${topics.length} core topics to synthesize an Examination Blueprint.`,
    };
  }
}
